development:
  adapter: postgresql
  encoding: unicode
  database: lucidly_development
  pool: 5
  host: localhost
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: lucidly_test
  pool: 5
  host: localhost
  username:
  password:

  adapter: postgresql
  encoding: unicode
  database: lucidly_production
  host: localhost
  pool: 5
  username:
  password:
